'use client';

import { useState } from 'react';
import { BadgeCheck, Edit3, Plus, Search, Trash2, UserPlus, Users } from 'lucide-react';
import { deletePlayerCategoryAssignment, deletePlayerCategoryLevel, savePlayerCategoryAssignment, savePlayerCategoryLevel } from '@/actions/player-categories';

type UserOption = { id: string; name: string | null; lastName: string | null; dni: string | null; phone: string | null; category: string | null };
type Assignment = { id: string; levelId: string; userId: string | null; externalName: string | null; externalPhone: string | null; publicNote: string | null; isPublished: boolean; user: Omit<UserOption, 'category'> | null };
type Level = { id: string; name: string; description: string | null; color: string; displayOrder: number; isPublished: boolean; assignments: Assignment[] };
const blankLevel = { id: '', name: '', description: '', color: '#10b981', displayOrder: 0, isPublished: true };
const blankPlayer = { id: '', levelId: '', mode: 'user', userId: '', externalName: '', externalPhone: '', publicNote: '', isPublished: true };

export default function PlayerCategoriesAdmin({ initialLevels, users }: { initialLevels: Level[]; users: UserOption[] }) {
  const [level, setLevel] = useState(blankLevel);
  const [player, setPlayer] = useState(blankPlayer);
  const [query, setQuery] = useState('');
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const act = async (fn: () => Promise<{ success: boolean; error?: string }>, reset?: () => void) => { setBusy(true); setMessage(''); const result = await fn(); setBusy(false); setMessage(result.success ? 'Cambios guardados.' : result.error || 'No se pudo completar.'); if (result.success) { reset?.(); window.location.reload(); } };
  const rows = initialLevels.flatMap((l) => l.assignments.map((a) => ({ ...a, level: l }))).filter((a) => `${a.user?.name || ''} ${a.user?.lastName || ''} ${a.externalName || ''} ${a.level.name}`.toLowerCase().includes(query.toLowerCase()));
  const editPlayer = (a: Assignment) => setPlayer({ id: a.id, levelId: a.levelId, mode: a.userId ? 'user' : 'external', userId: a.userId || '', externalName: a.externalName || '', externalPhone: a.externalPhone || '', publicNote: a.publicNote || '', isPublished: a.isPublished });
  return <div className="space-y-7 p-4 sm:p-8">
    <div><p className="text-xs font-black uppercase tracking-widest text-[var(--color-primary)]">Padrón deportivo</p><h1 className="text-3xl font-black text-slate-900">Categorías de jugadores</h1><p className="mt-1 text-slate-500">Indicá la categoría real de cada persona. Este módulo es independiente de las posiciones de torneos.</p></div>
    {message && <div className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">{message}</div>}
    <section className="grid gap-5 xl:grid-cols-[360px_1fr]">
      <form className="h-fit space-y-4 rounded-3xl border bg-white p-5 shadow-sm" onSubmit={(e) => { e.preventDefault(); act(() => savePlayerCategoryLevel({ ...level, id: level.id || undefined, displayOrder: Number(level.displayOrder) }), () => setLevel(blankLevel)); }}>
        <div className="flex items-center gap-2"><BadgeCheck className="text-[var(--color-primary)]" /><h2 className="font-black">{level.id ? 'Editar categoría' : 'Nueva categoría'}</h2></div>
        <input required placeholder="Ej: 6ta, 5ta, 4ta" value={level.name} onChange={(e) => setLevel({ ...level, name: e.target.value })} className="w-full rounded-xl border px-3 py-2.5" />
        <textarea placeholder="Descripción opcional" value={level.description} onChange={(e) => setLevel({ ...level, description: e.target.value })} className="w-full rounded-xl border px-3 py-2.5" />
        <div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold text-slate-500">Color<input type="color" value={level.color} onChange={(e) => setLevel({ ...level, color: e.target.value })} className="mt-1 h-10 w-full rounded border" /></label><label className="text-xs font-bold text-slate-500">Orden<input type="number" min="0" value={level.displayOrder} onChange={(e) => setLevel({ ...level, displayOrder: Number(e.target.value) })} className="mt-1 w-full rounded-xl border px-3 py-2" /></label></div>
        <label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={level.isPublished} onChange={(e) => setLevel({ ...level, isPublished: e.target.checked })} /> Visible públicamente</label>
        <div className="flex gap-2"><button disabled={busy} className="flex-1 rounded-xl bg-[var(--color-primary)] px-4 py-3 font-black text-[var(--color-primary-foreground)]"><Plus className="mr-1 inline h-4 w-4" />Guardar</button>{level.id && <button type="button" onClick={() => setLevel(blankLevel)} className="rounded-xl border px-4">Cancelar</button>}</div>
      </form>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{initialLevels.map((l) => <article key={l.id} className="rounded-3xl border bg-white p-5 shadow-sm"><div className="mb-4 h-2 rounded-full" style={{ backgroundColor: l.color }} /><div className="flex justify-between"><div><h3 className="text-xl font-black">{l.name}</h3><p className="text-sm text-slate-500">{l.assignments.length} jugadores · {l.isPublished ? 'Pública' : 'Oculta'}</p></div><span className="font-black text-slate-300">#{l.displayOrder}</span></div><p className="my-3 min-h-10 text-sm text-slate-500">{l.description || 'Sin descripción.'}</p><div className="flex gap-2"><button onClick={() => setLevel({ id: l.id, name: l.name, description: l.description || '', color: l.color, displayOrder: l.displayOrder, isPublished: l.isPublished })} className="rounded-lg border p-2" aria-label="Editar"><Edit3 className="h-4 w-4" /></button><button onClick={() => confirm(`¿Eliminar ${l.name}?`) && act(() => deletePlayerCategoryLevel(l.id))} className="rounded-lg border p-2 text-red-600" aria-label="Eliminar"><Trash2 className="h-4 w-4" /></button></div></article>)}</div>
    </section>
    <section className="grid gap-5 xl:grid-cols-[420px_1fr]">
      <form className="h-fit space-y-4 rounded-3xl border bg-white p-5 shadow-sm" onSubmit={(e) => { e.preventDefault(); act(() => savePlayerCategoryAssignment({ id: player.id || undefined, levelId: player.levelId, userId: player.mode === 'user' ? player.userId : null, externalName: player.mode === 'external' ? player.externalName : null, externalPhone: player.mode === 'external' ? player.externalPhone : null, publicNote: player.publicNote, isPublished: player.isPublished }), () => setPlayer(blankPlayer)); }}>
        <div className="flex items-center gap-2"><UserPlus className="text-[var(--color-primary)]" /><h2 className="font-black">{player.id ? 'Editar jugador' : 'Asignar jugador'}</h2></div>
        <select required value={player.levelId} onChange={(e) => setPlayer({ ...player, levelId: e.target.value })} className="w-full rounded-xl border px-3 py-2.5"><option value="">Seleccionar categoría...</option>{initialLevels.map((l) => <option key={l.id} value={l.id}>{l.name}</option>)}</select>
        <div className="grid grid-cols-2 rounded-xl bg-slate-100 p-1"><button type="button" disabled={Boolean(player.id)} onClick={() => setPlayer({ ...player, mode: 'user' })} className={`rounded-lg py-2 text-sm font-bold ${player.mode === 'user' ? 'bg-white shadow' : ''}`}>Registrado</button><button type="button" disabled={Boolean(player.id)} onClick={() => setPlayer({ ...player, mode: 'external' })} className={`rounded-lg py-2 text-sm font-bold ${player.mode === 'external' ? 'bg-white shadow' : ''}`}>No registrado</button></div>
        {player.mode === 'user' ? <select required value={player.userId} onChange={(e) => setPlayer({ ...player, userId: e.target.value })} className="w-full rounded-xl border px-3 py-2.5"><option value="">Seleccionar usuario...</option>{users.map((u) => <option key={u.id} value={u.id}>{`${u.name || ''} ${u.lastName || ''}`.trim()} {u.dni ? `· DNI ${u.dni}` : ''}</option>)}</select> : <div className="grid gap-3"><input required placeholder="Nombre y apellido" value={player.externalName} onChange={(e) => setPlayer({ ...player, externalName: e.target.value })} className="rounded-xl border px-3 py-2.5" /><input placeholder="Teléfono (solo admin)" value={player.externalPhone} onChange={(e) => setPlayer({ ...player, externalPhone: e.target.value })} className="rounded-xl border px-3 py-2.5" /></div>}
        <textarea placeholder="Nota pública opcional: categoría provisoria, evaluado..." value={player.publicNote} onChange={(e) => setPlayer({ ...player, publicNote: e.target.value })} className="w-full rounded-xl border px-3 py-2.5" />
        <label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={player.isPublished} onChange={(e) => setPlayer({ ...player, isPublished: e.target.checked })} /> Mostrar en la consulta pública</label>
        <div className="flex gap-2"><button disabled={busy || !initialLevels.length} className="flex-1 rounded-xl bg-slate-900 px-4 py-3 font-black text-white">Guardar asignación</button>{player.id && <button type="button" onClick={() => setPlayer(blankPlayer)} className="rounded-xl border px-4">Cancelar</button>}</div>
      </form>
      <div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="flex items-center gap-3 border-b p-4"><Search className="h-5 w-5 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar jugador o categoría..." className="w-full outline-none" /></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Jugador</th><th className="p-4">Categoría</th><th className="p-4">Visibilidad</th><th className="p-4 text-right">Acciones</th></tr></thead><tbody className="divide-y">{rows.map((a) => <tr key={a.id}><td className="p-4"><strong>{a.user ? `${a.user.name || ''} ${a.user.lastName || ''}`.trim() : a.externalName}</strong><small className="block text-slate-400">{a.user ? 'Usuario registrado' : `Externo${a.externalPhone ? ` · ${a.externalPhone}` : ''}`}</small></td><td className="p-4"><span className="rounded-full px-3 py-1 font-black text-white" style={{ backgroundColor: a.level.color }}>{a.level.name}</span></td><td className="p-4">{a.isPublished ? 'Público' : 'Oculto'}</td><td className="p-4 text-right"><button onClick={() => editPlayer(a)} className="mr-2 rounded-lg border p-2"><Edit3 className="h-4 w-4" /></button><button onClick={() => confirm('¿Quitar a este jugador del padrón?') && act(() => deletePlayerCategoryAssignment(a.id))} className="rounded-lg border p-2 text-red-600"><Trash2 className="h-4 w-4" /></button></td></tr>)}{!rows.length && <tr><td colSpan={4} className="p-10 text-center text-slate-400"><Users className="mx-auto mb-2" />No hay jugadores para mostrar.</td></tr>}</tbody></table></div></div>
    </section>
  </div>;
}
